version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "200MB"

  api1: &api
    build:
      context: .
      dockerfile: ./RinhaDeBackend.API/Dockerfile
    image: leonardohof/rinhabackend-2401
    hostname: api1
    container_name: api1
    environment:
      - ConnectionStrings__Default=Host=db;Database=postgres;User Id=postgres;Password=postgres;
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'
    networks:
      - rinha-network


networks:
  rinha-network: